/*
 * @Author Loris
 * @version 2019.03.13
 */
package team02;

public enum HalteBedingung {
	BIS_KREUZUNG_VORNE,
	BIS_KREUZUNG_MITTE,
	BIS_KREUZUNG_HINTEN,
	BIS_WAND,
	BIS_WAND_VORNE,
	BIS_WAND_LINKS,
	BIS_WAND_RECHTS,
	BIS_LINIE_SENKRECHT,
	BIS_LINIE_WAAGERECHT,
	BIS_DISTANZ_ERREICHT,
	BIS_DREHWINKEL_ERREICHT,
	BIS_ZEIT_ABGELAUFEN,
	BIS_NICHTS
}
