package team06.aurelia;

public enum Zustand {

    STARTZUSTAND,
    WURF_KURZ_VORBEREITEN,
    WURF_LANG_VORBEREITEN,
    KORBWURF_VORBEREITEN,
    WURFPOSITION,
    POSITION_WECHSELN,
    VORRUECKEN,
    RUECKWAERTS_AN_WAND,
    FANGPOSITION,
    ENDE,
    FEHLER

}
