package team06.aurelia;

public enum Zustand {

    STARTZUSTAND,
    BEREIT,
    WURF_KURZ,
    KURZRETOUR,
    WURF_LANG,
    VORWÄRTS,
    POSITION_WECHSELN,
    VORRUECKEN,
    RUECKWAERTS_AN_WAND,
    FANGPOSITION,
    SCHIESSPOSITION,
    STARTPOSITION,
    ENDE,
    FEHLER,
    WEITERFAHREN,
    START,
    NEUNZIGGRADLINKS,
    NEUNZIGGRADLINKS_2,
    NEUNZIGGRADRECHTS,
    NEUNZIGGRADRECHTS_2,
    HUNDERTACHZIGLINKS,
    YFAHREN,
    YFAHREN_2,
    GEGNERVORNE,
    WAND,
    RETOURRECHTS,
    RETOUR

}
